### ISSUE TITLE
Сверстать блок с поисковым запросом

### ISSUE THREAD

**Issue by LexorV** [Marketplace-of-graphic-images/frontend#32]

**Comment by udartapkom** [comment]
Свёрстана секция поиска. Добавлена некоторая логика, в общем **почти всё** готово для подключения к API.
Также обновлены глобальные переменные и актуализированы шрифты из нового пака Фигмы.
Сделаны кнопки, добавлены некоторые иконки (лупа, стрелка)

**Comment by udartapkom** [comment]
никаких эффектов наведения и плавности нет, ибо её нет и в Фигме
