### ISSUE TITLE
Подключить миксины и переменные SCSS и добавить цвета

### ISSUE THREAD

**Issue by LexorV** [Marketplace-of-graphic-images/frontend#4]

**Comment by udartapkom** [comment]
Список цветов:
$white-color: #ffffff;
$black-color: #060606;
$accent-color: #029992;
$accent_on_hover-color: #007873;
$disabled-color: #b5b5b5;
$link-color: #2263c4;
$error_background-color: #ffd1d1;
$error-color: #cd0b0b;

//используем файл с переменными
@use '../globalStyle/variables' as v;

//пример использования в селекторе
.App-header {
	background-color: v.$black-color;
}
