### ISSUE TITLE
Добавить шрифты

### ISSUE THREAD

**Issue by LexorV** [Marketplace-of-graphic-images/frontend#5]

**Comment by udartapkom** [comment]
//Подключаем миксины из набора "Типографика"
@use '../globalStyle/mixins.scss' as m;

//Список готовых шрифтов
Header
Body
Link
Code
Numbers

//Используем в селекторе
.App-header {
	@include m.Header;
}

//Универсальный миксин
@include m.fonts('Roboto-Thin', normal, 100, '../fonts/Roboto/', '.woff2');

//здесь нужно передать 
(Семейство, стиль, вес, путь к папке, тип)

//Используем в селекторе
.App-header {
font-family: Roboto-Thin;
}
